Updated to the current advertise/wrapper scripts

diff --git a/el6/osgvo-node-advertise b/el6/osgvo-node-advertise
--- a/el6/osgvo-node-advertise
+++ b/el6/osgvo-node-advertise
@@ -52,6 +52,13 @@ function advertise {
     fi
 }
 
+if [ "x$OSG_SINGULARITY_REEXEC" = "x" ]; then
+    info "This is a setup script for the OSG-FLOCK frontend."
+    info "In case of problems, contact Mats Rynge (rynge@isi.edu)"
+    info "Running in directory $PWD"
+else
+    info "Now running inside a singularity container"
+fi
 
 if [ "x$glidein_config" = "x" ]; then
     glidein_config="NONE"
@@ -60,18 +67,24 @@ else
     info "Arguments to the script: $@"
 fi
 
-info "This is a setup script for the OSG-FLOCK frontend."
-info "In case of problems, contact Mats Rynge (rynge@isi.edu)"
-
 if [ "$glidein_config" != "NONE" ]; then
     ###########################################################
     # import advertise and add_condor_vars_line functions
-    add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
-    source $add_config_line_source
+    if [ "x$add_config_line_source" = "x" ]; then
+        export add_config_line_source=`grep '^ADD_CONFIG_LINE_SOURCE ' $glidein_config | awk '{print $2}'`
+        export condor_vars_file=`grep -i "^CONDOR_VARS_FILE " $glidein_config | awk '{print $2}'`
+    fi
 
-    condor_vars_file=`grep -i "^CONDOR_VARS_FILE " $glidein_config | awk '{print $2}'`
+    source $add_config_line_source
 fi
 
+###########################################################
+# We have two env variables which can be added to in this
+# script to provide an expression for the START expression
+# and a general warnings string which gets published in the
+# ad. These are env variables until the end.
+export GLIDEIN_VALIDATION_EXPR="True"
+export GLIDEIN_VALIDATION_WARNINGS=""
 
 ###########################################################
 # attributes below this line
@@ -82,13 +95,14 @@ fi
 if [ "x$OSG_SINGULARITY_REEXEC" = "x" ]; then
     info "Checking for CVMFS availability and attributes..."
     for FS in \
-       oasis.opensciencegrid.org \
-       stash.osgstorage.org \
-       icecube.opensciencegrid.org \
-       xenon.opensciencegrid.org \
+       ams.cern.ch \
        atlas.cern.ch \
        cms.cern.ch \
-       ams.cern.ch \
+       icecube.opensciencegrid.org \
+       oasis.opensciencegrid.org \
+       singularity.opensciencegrid.org \
+       stash.osgstorage.org \
+       xenon.opensciencegrid.org \
     ; do
         FS_CONV=`echo "$FS" | sed 's/\./_/g'`
         FS_ATTR="HAS_CVMFS_$FS_CONV"
@@ -122,7 +136,12 @@ if [ "x$OSG_SINGULARITY_REEXEC" = "x" ]; then
             fi
         fi
     done
-    
+
+    # if it looks like we have CVMFS, make sure the START expression knows that
+    if [ -e /cvmfs ]; then
+        export GLIDEIN_VALIDATION_EXPR="HAS_CVMFS_oasis_opensciencegrid_org && HAS_CVMFS_singularity_opensciencegrid_org && HAS_CVMFS_stash_osgstorage_org"
+    fi
+
     # update timestamp?
     TS_ATTR="CVMFS_oasis_opensciencegrid_org_TIMESTAMP"
     TS_VAL=`(cat /cvmfs/oasis.opensciencegrid.org/osg/update.details  | egrep '^Update unix time:' | sed 's/.*: //') 2>/dev/null`
@@ -141,54 +160,126 @@ fi # OSG_SINGULARITY_REEXEC
 
 if [ "x$OSG_SINGULARITY_REEXEC" = "x" ]; then
     info "Checking for singularity..."
+
+    # some known singularity locations
+    for LOCATION in \
+        /util/opt/singularity/2.2.1/gcc/4.4/bin \
+        /util/opt/singularity/2.2/gcc/4.4/bin \
+        /uufs/chpc.utah.edu/sys/installdir/singularity/std/bin \
+    ; do
+        if [ -e "$LOCATION" ]; then
+            info " ... prepending $LOCATION to PATH"
+            export PATH="$LOCATION:$PATH"
+            break
+        fi
+    done
+
     HAS_SINGULARITY="False"
-    OSG_SINGULARITY_VERSION=`singularity --version 2>/dev/null`
+    export OSG_SINGULARITY_VERSION=`singularity --version 2>/dev/null`
     if [ "x$OSG_SINGULARITY_VERSION" != "x" ]; then
         HAS_SINGULARITY="True"
-        OSG_SINGULARITY_PATH=`which singularity`
+        export OSG_SINGULARITY_PATH=`which singularity`
     else
         # some sites requires us to do a module load first - not sure if we always want to do that
-        OSG_SINGULARITY_VERSION=`module load singularity >/dev/null 2>&1; singularity --version 2>/dev/null`
+        export OSG_SINGULARITY_VERSION=`module load singularity >/dev/null 2>&1; singularity --version 2>/dev/null`
         if [ "x$OSG_SINGULARITY_VERSION" != "x" ]; then
             HAS_SINGULARITY="True"
-            OSG_SINGULARITY_PATH=`module load singularity >/dev/null 2>&1; which singularity`
+            export OSG_SINGULARITY_PATH=`module load singularity >/dev/null 2>&1; which singularity`
+        else
+            info "Unable to find singularity in PATH=$PATH"
         fi
     fi
+    if [ "x$HAS_SINGULARITY" = "xTrue" ]; then
+        info "Singularity binary appears present and claims to be version $OSG_SINGULARITY_VERSION"
+    fi
+
+    # default image for this glidein
+    export OSG_SINGULARITY_IMAGE_DEFAULT="/cvmfs/singularity.opensciencegrid.org/rynge/osgvo:el6"
 
     # for now, we will only advertise singularity on nodes which can access cvmfs
-    if [ ! -e /cvmfs/cernvm-prod.cern.ch/cvm3 ]; then
+    if [ ! -e "$OSG_SINGULARITY_IMAGE_DEFAULT" ]; then
+        info "Default singularity image, $OSG_SINGULARITY_IMAGE_DEFAULT, does not appear to exist"
         HAS_SINGULARITY="False"
     fi
 
-    if [ "x$HAS_SINGULARITY" = "xTrue" -a "x$OSG_SINGULARITY_VERSION" != "x" -a "x$OSG_SINGULARITY_PATH" != "x" ]; then
-        advertise OSG_SINGULARITY_VERSION "$OSG_SINGULARITY_VERSION" "S"
-        advertise OSG_SINGULARITY_PATH "$OSG_SINGULARITY_PATH" "S"
+    # Let's do a simple singularity test by echoing something inside, and then
+    # grepping for it outside. This takes care of some errors which happen "late"
+    # in the execing, like:
+    # ERROR  : Could not identify basedir for home directory path: /
+    if [ "x$HAS_SINGULARITY" = "xTrue" ]; then
+        info "$OSG_SINGULARITY_PATH exec --home $PWD:/srv --bind /cvmfs --pwd /srv --scratch /var/tmp --scratch /tmp --containall $OSG_SINGULARITY_IMAGE_DEFAULT echo Hello World | grep Hello World"
+        if ! ($OSG_SINGULARITY_PATH exec --home $PWD:/srv \
+                                         --bind /cvmfs \
+                                         --pwd /srv \
+                                         --scratch /var/tmp \
+                                         --scratch /tmp \
+                                         --containall \
+                                         "$OSG_SINGULARITY_IMAGE_DEFAULT" \
+                                         echo "Hello World" \
+                                         | grep "Hello World") 1>&2 \
+        ; then
+            # singularity simple exec failed - we are done
+            info "Simple singularity exec inside $OSG_SINGULARITY_IMAGE_DEFAULT failed."
+            HAS_SINGULARITY="False"
+        fi
     fi
-    advertise HAS_SINGULARITY "$HAS_SINGULARITY" "C"
-    
-    # if we have singularity, we should re-exec this script within the default
+
+    # If we still think we have singularity, we should re-exec this script within the default
     # container so that we can advertise that environment
     if [ "x$HAS_SINGULARITY" = "xTrue" ]; then
         # We want to map the full glidein dir to /srv inside the container. This is so 
         # that we can rewrite env vars pointing to somewhere inside that dir (for
         # example, X509_USER_PROXY)
-        export SING_OUTSIDE_BASE_DIR=`echo "$PWD" | sed -E "s;(.*/glide_[a-zA-Z0-9]+)/.*;\1;"`
+        export SING_OUTSIDE_BASE_DIR=`echo "$PWD" | sed -E "s;(.*/glide_[a-zA-Z0-9]+).*;\1;"`
 
         # build a new command line, with updated paths
         CMD=""
         for VAR in $0 "$@"; do
-            VAR=`echo " $VAR" | sed -E "s;.*/glide_[a-zA-Z0-9]+/(.*);/srv/\1;"`
+            VAR=`echo " $VAR" | sed -E "s;.*/glide_[a-zA-Z0-9]+(.*);/srv\1;"`
             CMD="$CMD $VAR"
         done
 
         # let "inside" script know we are re-execing
         export OSG_SINGULARITY_REEXEC=1
-        info "$OSG_SINGULARITY_PATH exec --bind /cvmfs --bind $SING_OUTSIDE_BASE_DIR:/srv --pwd /srv --scratch /var/tmp --scratch /tmp --containall /cvmfs/cernvm-prod.cern.ch/cvm3/ $CMD"
-        exec $OSG_SINGULARITY_PATH exec --bind /cvmfs --bind $SING_OUTSIDE_BASE_DIR:/srv --pwd /srv --scratch /var/tmp --scratch /tmp --containall /cvmfs/cernvm-prod.cern.ch/cvm3/ $CMD
+        info "$OSG_SINGULARITY_PATH exec --home $SING_OUTSIDE_BASE_DIR:/srv --bind /cvmfs --pwd /srv --scratch /var/tmp --scratch /tmp --containall $OSG_SINGULARITY_IMAGE_DEFAULT $CMD"
+        if $OSG_SINGULARITY_PATH exec --home $SING_OUTSIDE_BASE_DIR:/srv \
+                                      --bind /cvmfs \
+                                      --pwd /srv \
+                                      --scratch /var/tmp \
+                                      --scratch /tmp \
+                                      --containall \
+                                      "$OSG_SINGULARITY_IMAGE_DEFAULT" \
+                                      $CMD \
+        ; then
+            # singularity worked - exit here as the rest script ran inside the container
+            exit $?
+        fi
     fi
+    
+    # if we get here, singularity is not available or not working
+    advertise HAS_SINGULARITY "False" "C"
+
 else
-    info "Already running inside singularity"
-    advertise OSG_SINGULARITY_OSGVO_IMAGE "True" "C"
+
+    # delay the advertisement until here to make sure singularity actually works
+    advertise HAS_SINGULARITY "True" "C"
+    advertise OSG_SINGULARITY_VERSION "$OSG_SINGULARITY_VERSION" "S"
+    advertise OSG_SINGULARITY_PATH "$OSG_SINGULARITY_PATH" "S"
+    advertise OSG_SINGULARITY_IMAGE_DEFAULT "$OSG_SINGULARITY_IMAGE_DEFAULT" "S"
+   
+    # fix up the env
+    for key in X509_USER_PROXY X509_USER_CERT _CONDOR_MACHINE_AD _CONDOR_JOB_AD \
+               _CONDOR_SCRATCH_DIR _CONDOR_CHIRP_CONFIG _CONDOR_JOB_IWD \
+               add_config_line_source condor_vars_file ; do
+        eval val="\$$key"
+        val=`echo "$val" | sed -E "s;$SING_OUTSIDE_BASE_DIR(.*);/srv\1;"`
+        eval $key=$val
+    done
+        
+    export add_config_line_source=`echo "$add_config_line_source" | sed -E "s;.*/glide_[a-zA-Z0-9]+(.*);/srv\1;"`
+    export condor_vars_file=`echo "$condor_vars_file" | sed -E "s;.*/glide_[a-zA-Z0-9]+(.*);/srv\1;"`
+    info "Updated glidein config to paths inside the container: add_config_line_source=$add_config_line_source condor_vars_file=$condor_vars_file"
+
 fi
 
 # operating system
@@ -244,10 +335,6 @@ advertise OSGVO_OS_KERNEL "$OS_KERNEL" "S"
 # cpu info
 CPU_MODEL=`cat /proc/cpuinfo | grep -i "^model name" | head -n 1 | sed -r 's/[a-zA-Z \t]+:[ ]*//'`
 advertise OSGVO_CPU_MODEL "$CPU_MODEL" "S"
-
-# available disk space
-OSGVO_PILOT_DF=`df -kP . | awk '{if (NR==2) print $4}'`
-advertise OSGVO_PILOT_DF "$OSGVO_PILOT_DF" "I"
 
 
 ###########################################################
@@ -336,7 +423,7 @@ fi
 
 info "Attempting to determine if tcsh is available and works..."
 cat >csh.test <<EOF
-#!/bin/tcsh -x -f
+#!/bin/tcsh -f
 /bin/true
 EOF
 chmod 755 csh.test
@@ -550,32 +637,44 @@ advertise HAS_BLAST "$HAS_BLAST" "C"
 
 ##################
 # PHSW (Matt Snowball)
+#
+#info "Checking for PHSW availability..."
+#
+#PHSW_RESULT="True"
+#PHSWDIR=/cvmfs/oasis.opensciencegrid.org/osg/projects/phenix/snowball/phnxsw
+#
+#if [ -e /cvmfs/oasis.opensciencegrid.org/osg/projects/phenix/snowball/phnxsw/bin/set_grid_env.sh ]; then
+#
+#    if ! (source $PHSWDIR/bin/set_grid_env.sh && grid-proxy-init -version && voms-proxy-init -version) 1>&2 ; then
+#        PHSW_RESULT="False"
+#    fi
+#    
+#    (source $PHSWDIR/bin/set_grid_env.sh && globus-url-copy -version) 1>&2
+#    RC=$?
+#    if [ "x$RC" != "x0" -a "x$RC" != "x1" ]; then
+#        PHSW_RESULT="False"
+#    fi
+#    
+#    if ! (source $PHSWDIR/bin/set_grid_env.sh && root.exe -l -b -q) 1>&2 ; then
+#        PHSW_RESULT="False"
+#    fi
+#else
+#    PHSW_RESULT="False"
+#fi
+#
+#advertise HAS_PHSW "$PHSW_RESULT" "C"
 
-info "Checking for PHSW availability..."
-
-PHSW_RESULT="True"
-PHSWDIR=/cvmfs/oasis.opensciencegrid.org/osg/projects/phenix/snowball/phnxsw
-
-if [ -e /cvmfs/oasis.opensciencegrid.org/osg/projects/phenix/snowball/phnxsw/bin/set_grid_env.sh ]; then
-
-    if ! (source $PHSWDIR/bin/set_grid_env.sh && grid-proxy-init -version && voms-proxy-init -version) 1>&2 ; then
-        PHSW_RESULT="False"
-    fi
-    
-    (source $PHSWDIR/bin/set_grid_env.sh && globus-url-copy -version) 1>&2
-    RC=$?
-    if [ "x$RC" != "x0" -a "x$RC" != "x1" ]; then
-        PHSW_RESULT="False"
-    fi
-    
-    if ! (source $PHSWDIR/bin/set_grid_env.sh && root.exe -l -b -q) 1>&2 ; then
-        PHSW_RESULT="False"
-    fi
+##################
+# mostly done - update START validation expressions and warnings attribute
+if [ -e .stop-glidein.stamp -o -e ../.stop-glidein.stamp ]; then
+    advertise OSG_NODE_VALIDATED "False" "C"
+    advertise OSG_NODE_WARNINGS "Node is shutting down due to stop-glidein file" "S"
 else
-    PHSW_RESULT="False"
+    advertise OSG_NODE_VALIDATED "$GLIDEIN_VALIDATION_EXPR" "C"
+    if [ "x$GLIDEIN_VALIDATION_WARNINGS" != "x" ]; then
+        advertise OSG_NODE_WARNINGS "$GLIDEIN_VALIDATION_WARNINGS" "S"
+    fi
 fi
-
-advertise HAS_PHSW "$PHSW_RESULT" "C"
 
 
 ##################
